// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import { get } from "http";

/*
All of these responses where generated by GPT using a prompt similar to:

```
Here's a JavaScript string literal template:

`I couldn't find a ${item} on your ${list} list.`

Create a JavaScript array with 7 variations of the template.
The variations should be helpful, creative, clever, and very friendly.
The variations should always use the back tick `` syntax.
The variations should always include ${item} and ${list} variables.
```

7 variations were asked for so that we can remove the 2 we like the least.
*/

/**
 *
 */
export function greeting(): string {
  return getRandomResponse([
    "Welcome to Copilot AI Assistance! Type /reset to delete all existing lists of company names.",
    "Hello! I'm Copilot AI Assistance. Use /reset to delete all your lists of company names.",
    "Hi there! I'm here to help you manage company info. Use /reset to delete all lists of company names.",
    "Greetings! I'm Copilot AI Assistance. Type /reset to delete all your list.",
    "Hey there! Copilot AI Assistance here. You can use /reset to delete all lists of company names.",
  ]);
}

export function promptReturned(): string {
  return getRandomResponse([
    "Just a moment while I fetch the prompt response from Copilot AI for the company you mentioned. Thank you for your patience.",
    "Please hold on for a brief moment as I retrieve the prompt response from Copilot AI regarding the company you mentioned.",
    "Allow me a moment to access the prompt response from Copilot AI for the company you mentioned. Your patience is appreciated.",
    "I'm currently retrieving the prompt response from Copilot AI for the company you mentioned. It will only take a moment, thank you for waiting.",
    "I'm accessing the prompt response from Copilot AI for the company you mentioned. Please bear with me for a moment while I retrieve the information.",
  ]);
}

export function waitingForResponse(): string {
  return getRandomResponse([
    "Understood. I am fetching your answer. Please wait a moment.",
    "I am loading your answer. Please wait a moment.",
    "I am processing your request. Please wait a moment.",
    "I am retrieving your answer. Please wait a moment.",
  ]);
}

/**
 *
 */
export function reset(): string {
  return getRandomResponse([
    "Resetting conversation history. All history has been deleted.",
    "Starting fresh. Conversation history has been reset.",
    "Cleaning slate. All conversation history has been cleared.",
    "Resetting. All conversation history has been removed.",
  ]);
}

/**
 * returns a random response from the list of responses
 * @returns
 */
export function entityNotFound(): string {
  return getRandomResponse([
    "I'm sorry, but I couldn't find any information about the entity you mentioned. Please verify the entity or provide the correct name or ticker symbol, and I'll do my best to help you.",
    "Apologies, but I don't have any information on the entity you mentioned. Please double-check the entity or provide the correct name or ticker symbol, and I'll try my best to support you.",
    "I regret to inform you that I'm unable to find any information about the entity you mentioned. Kindly verify the entity or provide the correct name or ticker symbol, and I'll make every effort to assist you.",
    "I apologize for the inconvenience, but I don't have any knowledge about the entity you mentioned. It's possible that the entity you specified is not part of the list of tracked organizations. Kindly verify the entity or provide the correct name or ticker symbol, and I'll make every effort to assist you.",
    "I'm sorry, but I couldn't find any information about the entity you mentioned. Please verify the entity or provide the correct name or ticker symbol, and I'll do my best to help you.",
  ]);
}

export function promptNotFound(): string {
  return getRandomResponse([
    "I'm sorry, but I couldn't find any answers to your question.",
    "Apologies, but I don't have any answers to your question.",
    "I regret to inform you that I'm unable to find any answers to your question.",
    "I apologize for the inconvenience, but I don't have any answers to your question.",
  ]);
}

/**
 * @param list
 * @param item
 */
export function companyNotFound(companyName: string): string {
  return getRandomResponse([
    `I'm sorry, but I'm not familiar with ${companyName}. It's likely that the company you mentioned is not included in the Copilot database. Please verify the company name or provide the correct name or ticker symbol, and I'll do my best to help you.`,
    `Apologies, but I don't have any information on ${companyName}. It's probable that the company you mentioned isn't within the scope of our coverage. Please double-check the company name or provide the correct name or ticker symbol, and I'll try my best to support you.`,
    `I regret to inform you that I'm unfamiliar with ${companyName}. It's possible that the company you specified is not part of the list of tracked organizations. Kindly verify the company name or provide the correct name or ticker symbol, and I'll make every effort to assist you.`,
    `I apologize for the inconvenience, but I don't have any knowledge about ${companyName}. It's likely that the company you referred to is not monitored by the org. Please ensure the accuracy of the company name or provide the correct name or ticker symbol, and I'll do my utmost to provide you with assistance.`,
    `I'm sorry, but I don't have any information regarding ${companyName}. It's possible that the company you mentioned is not within the realm of our coverage. Please double-check the company name or provide the correct name or ticker symbol, and I'll make every effort to support you.`,
  ]);
}

/**
 * @param companyName
 */
export function searchingForCompany(companyName: string): string {
  return getRandomResponse([
    `Additionally, utilizing the organizations' knowledge database, I can furnish supplementary details about ${companyName}.`,
    `Furthermore, with access to our organization's knowledge database, I can offer further insights on ${companyName}.`,
    `In addition, leveraging our organization's knowledge database allows me to provide extra information about ${companyName}.`,
    `Furthermore, by tapping into our organization's knowledge database, I can deliver additional details regarding ${companyName}.`,
    `Moreover, I can tap into our organization's knowledge database to offer supplementary information about ${companyName}.`,
  ]);
}

/**
 * @param list
 * @param item
 */
export function companyFound(companyName: string): string {
  return getRandomResponse([
    `Great! I found ${companyName} in the Copilot database.`,
    `Fantastic! I  was able to found ${companyName} in the Copilot database.`,
    `Excellent! I found ${companyName} in the Copilot database.`,
    `Wonderful! I found ${companyName} in the Copilot database.`,
    `Awesome! I found ${companyName} in the Copilot database.`,
  ]);
}

/**
 *
 */
export function noListsFound(): string {
  return getRandomResponse([
    "You don't have any lists of company names yet.",
    "You haven't made any lists of company names yet.",
    "It looks like you don't have any lists of company names yet.",
    "No lists of company names have been made yet.",
    "You don't have any lists of company names set up yet.",
  ]);
}

/**
 * @param action
 */
export function unknownAction(action: string): string {
  return getRandomResponse([
    `I'm sorry, I'm not sure how to ${action}.`,
    `I don't know the first thing about ${action}.`,
    `I'm not sure I'm the best person to help with ${action}.`,
    `I'm still learning about ${action}, but I'll try my best.`,
    `I'm afraid I'm not experienced enough with ${action}.`,
  ]);
}

/**
 *
 */
export function offTopic(): string {
  return getRandomResponse([
    "Besides, in addition to providing general response like Chat GPT to your question, I can also extract the company name from your chat input, and then provide the detailed information about that company using our organization's database. Would you like to try me?",
    "In addition to providing general response like Chat GPT to your question, I can also extract the company name from your chat input, and then provide the detailed information about that company using our organization's database. Would you like to try me?",
    "Furthermore, in addition to providing general response like Chat GPT to your question, I can also extract the company name from your chat input, and then provide the detailed information about that company using our organization's database. Would you like to try me?",
    "Moreover, in addition to providing general response like Chat GPT to your question, I can also extract the company name from your chat input, and then provide the detailed information about that company using our organization's database. Would you like to try me?",
  ]);
}

/**
 * Get random response from the provided list of options
 * @param companyName
 * @returns
 */
export function chatGPTError(companyName: string | null): string {
  return companyName
    ? getRandomResponse([
        `Apologies, I'm currently unable to retrieve a response from Chat GPT. However, I can tap into our organization's knowledge base to gather supplementary insights about ${companyName}.`,
        `Regrettably, I'm unable to fetch a response from Chat GPT right now. Nonetheless, I have the ability to delve into our organization's knowledge base and extract further details about ${companyName}.`,
        `I apologize for the inconvenience, but I'm currently unable to obtain a response from Chat GPT. However, I can explore our organization's knowledge base to find additional information about ${companyName}.`,
        `I'm sorry, but I'm presently unable to access a response from Chat GPT. Nevertheless, I can consult our organization's knowledge base to uncover more details about ${companyName}.`,
        `Unfortunately, I'm unable to retrieve a response from Chat GPT at the moment. However, I can delve into our organization's knowledge base to extract supplementary information about ${companyName}.`,
      ])
    : getRandomResponse([
        "Apologies, I'm currently unable to retrieve a response from Chat GPT. Please try again later.",
        "Regrettably, I'm unable to fetch a response from Chat GPT right now. Please try again later.",
        "I apologize for the inconvenience, but I'm currently unable to obtain a response from Chat GPT. Please try again later.",
        "I'm sorry, but I'm presently unable to access a response from Chat GPT. Please try again later.",
        "Unfortunately, I'm unable to retrieve a response from Chat GPT at the moment. Please try again later.",
      ]);
}

export function openAIRateLimited(): string {
  return getRandomResponse([
    "I'm sorry, but I'm currently unable to access OpenAI. Please try again later.",
    "Regrettably, I'm unable to fetch a response from OpenAI right now. Please try again later.",
    "I apologize for the inconvenience, but I'm currently unable to obtain a response from OpenAI. Please try again later.",
    "I'm sorry, but I'm presently unable to access a response from OpenAI. Please try again later.",
    "Unfortunately, I'm unable to retrieve a response from OpenAI at the moment. Please try again later.",
  ]);
}

export function processingUploadedDocuments(): string {
  return getRandomResponse([
    "Analyzing the uploaded documents. Please wait.",
    "Processing the uploaded documents. Hang tight!",
    "Compiling the uploaded documents. Hold on a moment.",
    "Scouring the uploaded documents. Stay tuned!",
    "Searching the uploaded documents. Please hold.",
  ]);
}

export function contentRetrievalInProgress(): string {
  return getRandomResponse([
    "Retrieving the requested information from the provided content. Please wait.",
    "Fetching the requested information from the provided content. Hang tight!",
    "Compiling the requested information from the provided content. Hold on a moment.",
    "Scouring the requested information from the provided content. Stay tuned!",
    "Searching the requested information from the provided content. Please hold.",
  ]);
}

export function noUploadedDocument(): string {
  return getRandomResponse([
    "Since no documents were uploaded, I'll use the ingested documents saved in Azure Blob Storage.",
    "As no documents were uploaded, I'll utilize the ingested documents saved in Azure Blob Storage.",
    "Since no documents were uploaded, I'll refer to the ingested documents saved in Azure Blob Storage.",
  ]);
}

/**
 * Get an error response for missing parameters need to be configured for the PDF command.
 * @param command
 * @returns
 */
export function pdfMissingParameters(): string {
  return "Error occurred when trying to analyze PDF document. Please ensure a PDF is uploaded and you are in a direct conversation with Copilot. Use common prompts as “summarize”, or you can ask a question.";
}

export function multipleEntitiesFound(
  company: string,
  companies: string[]
): string {
  const listOfCompanies = companies.join(", ");
  return `I found multiple companies similiar to <i>${company}</i>: <b>${listOfCompanies}</b>. \n\n<br>Let me know if you want to get more details about any of them.`;
}

/**
 * @param responses
 */
function getRandomResponse(responses: string[]): string {
  const i = Math.floor(Math.random() * (responses.length - 1));
  // eslint-disable-next-line security/detect-object-injection
  return responses[i];
}
